### ISSUE TITLE
remove reliance on dotenv

### ISSUE THREAD

**Issue by bgrayburn** [getzep/graphiti#211]
I'm trying to modify and run the wizard of oz example. I use direnv to set up env vars so remove the dotenv import. Now when I run the runner it complains that dotenv isn't installed because it's imported in `graphiti_core/graphiti.py`. Looks like either the docs need to be updated to say that dotenv is the only way to use graphiti, or dotenv is removed from the core library and leave it up to the user to figure out how they want to configure their code. I'd strongly prefer the second.

Thank you very much for creating this awesome application.

**Comment by bgrayburn** [comment]
actually I'm not sure why `dotenv` is in `graphiti_core/graphiti.py` as `os.environ` doesn't appear anywhere but in example files which already import `dotenv`.

**Comment by prasmussen15** [comment]
Hey, thanks for pointing this out!

We use dotenv to load dependencies for the Graphiti library. We've discussed removing it internally so you might see this in a future release. However, since we are only loading the dependencies with `dotenv` as long as the dependency is installed you should be able to just load env vars with whatever method you prefer. The current approach in the library is a fallback so things will still work if the end user forgets to load their own dependencies from a `.env` file. Again, we may remove this fallback in a future release

**Comment by bgrayburn** [comment]
Thank you for the response. Want to ask a question for clarity. By dependencies do you mean env vars? Or libraries? I'm unaware of `dotenv`'s ability to install libraries, but want to make sure we aren't overloading the word dependency here since we're talking about both env vars and libraries.

Apart from my request to remove dotenv since no env vars seem to be used within graphiti-core, my confusion is still that when I install qraphiti-core, I also have to install `dotenv` separately. If it's a dependency of graphiti-core, why isn't  it installed with graphiti-core? (installing with pip btw).

**Comment by prasmussen15** [comment]
Yes, `dotenv` will load the variables from the `.env` file.

The issue with the latter paragraph is something on our end that will be fixed with the next Graphiti release. Right now doting is flagged as a dev-only dependency when it should be a core dependency.

**Comment by bgrayburn** [comment]
Got it, thanks for the clarification and looking forward to the fix (and
potential future removal) :D
